dist: trusty
sudo: required
language: php
php:
  - '7.1.3'
  - '7.2'
  - nightly

before_script:
  - cp ./.env.example ./.env
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x ./composer.phar
  - ./composer.phar --version
  - ./composer.phar install --dev
  - docker-compose up -d

script:

after_sucess:
