version: '3'
services:

  # The Application
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=5432"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:80

  # The Database
  database:
    image: postgres:9.6
    volumes:
      - dbdata:/var/lib/pgsql
    environment:
      - "POSTGRES_USER=travis"
      - "POSTGRES_PASSWORD=travis123!"
      - "POSTGRES_DB=travis"
    ports:
        - "54321:5432"

volumes:
  dbdata:
